name: Run tests

env:
  OS: ubuntu-latest
  
on: push

jobs:
  install_dependency_and_run_test:
    runs-on: ubuntu-latest
    steps:
      - name: "Скачиваем Selenoid"
        run: curl -s https://aerokube.com/cm/bash  | bash
        
      - name: "Даем права на запуск Selenoid"
        run: chmod +x ./cm
        
      - name: "Запускаем Selenoid"
        run: ./cm selenoid start --vnc
        
      - name: "Запускаем Selenoid-ui"
        run: ./cm selenoid-ui start
        
      - name: "Используем main репозиторий"
        uses: actions/checkout@v1
        
      - name: "Запускаем тесты"
        run: mvn clean test
        
      - name: "Генерируем аллюр-репорт"
        uses: simple-elf/allure-report-action@master
        id: allure-report
        with:
          allure_results: allure-results
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
          
      - name: "Пушим аллюр-репорт в ветку gh-pages"
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
